"""Generate the browsable corpus index from figure-program metadata.

Metadata is read from SOURCE with `ast`, not by importing: listing 33 figures
should not cost 33 renders, and a figure that is mid-repair should still appear
in the index rather than silently vanishing from it. That second property is
the reason this is not just a loop over `load_program`.

    build_gallery(figures_dir) -> markdown
    write_gallery(figures_dir) -> path to figures/out/GALLERY.md
    write_readme_gallery(readme, figures_dir) -> the README's thumbnail grid
"""

from __future__ import annotations

import ast
from pathlib import Path

from .regress import artifact_dir, discover_programs

#: subjects in reading order; anything else sorts after, alphabetically
SUBJECT_ORDER = ["complex", "signals", "linalg", "dynamics", "optim",
                 "probability", "statmech", "infotheory", "circuits"]

SUBJECT_BLURB = {
    "complex": "Conformal maps, the Riemann sphere, contour integration.",
    "signals": "Sampling, spectra, and the geometry of transfer functions.",
    "linalg": "Matrices as geometry: the four readings, low rank, conditioning.",
    "dynamics": "Flows, bifurcations, and stochastic trajectories.",
    "optim": "What actually governs convergence.",
    "probability": "Densities under maps, and where the mass really lives.",
    "statmech": "Order parameters and phase transitions.",
    "infotheory": "Typicality, and why the mode is not the story.",
    "circuits": "Transformer internals as computation graphs.",
}


def _string_field(tree: ast.Module, name: str) -> str | None:
    """Read a module-level string assignment without executing the module.

    Handles the two spellings the corpus uses: a bare string, and the
    implicitly-concatenated `NAME = ("a" "b")` form that long CLAIMs take.
    """
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(isinstance(t, ast.Name) and t.id == name for t in node.targets):
            continue
        v = node.value
        if isinstance(v, ast.Constant) and isinstance(v.value, str):
            return v.value
        # ("part " "part") parses as a single Constant, but an explicit
        # a + b concatenation does not; fold that too rather than dropping it.
        if isinstance(v, ast.BinOp) and isinstance(v.op, ast.Add):
            try:
                return ast.literal_eval(v)
            except Exception:
                return None
    return None


def _subject(program: Path, figures_dir: Path) -> str:
    parent = program.parent.resolve()
    return "" if parent == figures_dir.resolve() else parent.name


def _sort_key(subject: str) -> tuple[int, str]:
    return ((SUBJECT_ORDER.index(subject), "") if subject in SUBJECT_ORDER
            else (len(SUBJECT_ORDER), subject))


def _entries(figures_dir: Path) -> dict[str, list[tuple[str, str, str]]]:
    """subject -> sorted [(stem relative to out/, claim, exposition)]."""
    out_root = figures_dir / "out"
    entries: dict[str, list[tuple[str, str, str]]] = {}
    for program in discover_programs(figures_dir):
        tree = ast.parse(program.read_text(), str(program))
        claim = _string_field(tree, "CLAIM") or "_(no CLAIM)_"
        prose = (_string_field(tree, "EXPOSITION")
                 or _string_field(tree, "PROBES")
                 or "_(no EXPOSITION yet)_")
        rel = artifact_dir(program, figures_dir).relative_to(out_root)
        stem = program.stem if str(rel) == "." else str(rel / program.stem)
        entries.setdefault(_subject(program, figures_dir), []).append(
            (stem, claim.strip(), prose.strip()))
    return {k: sorted(v) for k, v in entries.items()}


def build_gallery(figures_dir: str | Path) -> str:
    figures_dir = Path(figures_dir)
    entries = _entries(figures_dir)
    n = sum(len(v) for v in entries.values())
    lines = [
        "# Figure gallery", "",
        f"{n} figures. Generated by `make gallery` — **do not edit.**", "",
        "Each card shows the default cream render; the `_transparent` SVG is "
        "ink on alpha, for embedding in a document that owns its own ground.",
        "",
    ]
    for subject in sorted(entries, key=_sort_key):
        lines += [f"## {subject or 'unbinned'}", ""]
        if blurb := SUBJECT_BLURB.get(subject):
            lines += [f"*{blurb}*", ""]
        for stem, claim, prose in entries[subject]:
            name = Path(stem).name
            lines += [
                f"### {name}", "",
                f"![{name}]({stem}.png)", "",
                f"**Claim.** {claim}", "",
                prose, "",
                f"[cream svg]({stem}.svg) · "
                f"[transparent svg]({stem}_transparent.svg) · "
                f"[readback]({stem}.readback.md)", "",
                "---", "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def write_gallery(figures_dir: str | Path) -> Path:
    figures_dir = Path(figures_dir)
    path = figures_dir / "out" / "GALLERY.md"
    path.write_text(build_gallery(figures_dir))
    return path


# --- the README thumbnail grid ---------------------------------------------
#
# Inline <img> in paragraphs, NOT a <table>: GitHub's markdown stylesheet puts
# a 1px border and zebra striping on every table cell in a README, so a table
# grid frames each thumbnail in a grey box and tints alternate rows. Paragraphs
# get no chrome. The cost is that the browser, not us, decides where a row
# wraps -- so rows are justified to land UNDER the column width, never at it.

README_START = "<!-- gallery:start -->"
README_END = "<!-- gallery:end -->"
#: GitHub's README column is ~890px; leave headroom so no row can rewrap
CONTENT_WIDTH_PX = 840
ROW_TARGET_HEIGHT_PX = 230
#: the single collapsed space between two inline <img> tags
_IMG_GAP_PX = 5
#: a lone wide figure on the last row would otherwise justify to a banner
_MAX_ROW_STRETCH = 1.3


def justify_rows(aspects: list[float], content_width: float = CONTENT_WIDTH_PX,
                 target_h: float = ROW_TARGET_HEIGHT_PX,
                 ) -> list[list[tuple[int, int]]]:
    """Justified layout, the photo-gallery algorithm.

    Fill a row, then solve for the height that makes it exactly `content_width`
    wide. Ragged aspect ratios -- this corpus runs 0.88 to 4.07 -- come out as a
    flush grid, and every image in a row shares a height, so inline images sit
    on one baseline.

    The break decision is not pure greed: at the item that overflows, keep it
    only if doing so lands CLOSER to the target height than stopping short.
    Pure greed put four figures spanning 6.4 into one row and rendered them at
    131px -- flush, and far too small to read.

    Returns rows of (index, height_px, filled), where `filled` is False for a
    short trailing row -- one whose images cannot span the width even at the
    target height. Those get centred rather than left-hanging.
    """
    def height(span: float, n: int) -> float:
        return (content_width - _IMG_GAP_PX * (n - 1)) / span

    groups: list[list[int]] = []
    row: list[int] = []
    total = 0.0
    for i, a in enumerate(aspects):
        if row and (total + a) * target_h >= content_width:
            with_it = abs(height(total + a, len(row) + 1) - target_h)
            without = abs(height(total, len(row)) - target_h)
            if without <= with_it:
                groups.append(row)
                row, total = [], 0.0
        row.append(i)
        total += a
        if height(total, len(row)) <= target_h:
            groups.append(row)
            row, total = [], 0.0
    if row:
        groups.append(row)

    out = []
    for idx in groups:
        h = height(sum(aspects[i] for i in idx), len(idx))
        filled = h <= target_h * _MAX_ROW_STRETCH
        out.append([(i, int(min(h, target_h * _MAX_ROW_STRETCH)), filled)
                    for i in idx])
    return out


def _aspect(png: Path) -> float:
    """Fall back to 3:2 for a figure whose baseline is not on disk yet -- the
    grid should degrade, not crash, on a figure that has never been rendered."""
    try:
        from PIL import Image
        with Image.open(png) as im:
            return im.width / im.height
    except Exception:
        return 1.5


def build_readme_gallery(figures_dir: str | Path) -> str:
    figures_dir = Path(figures_dir)
    entries = _entries(figures_dir)
    out = []
    for subject in sorted(entries, key=_sort_key):
        rows = entries[subject]
        aspects = [_aspect(figures_dir / "out" / f"{stem}.png")
                   for stem, _, _ in rows]
        out += [f"### {subject or 'unbinned'}", ""]
        if blurb := SUBJECT_BLURB.get(subject):
            out += [f"*{blurb}*", ""]
        for band in justify_rows(aspects):
            imgs = []
            for i, h, _ in band:
                stem, _, _ = rows[i]
                name = Path(stem).name
                imgs.append(
                    f'<a href="figures/out/GALLERY.md#{name}">'
                    f'<img src="figures/out/{stem}.png" '
                    f'alt="{name}" height="{h}"></a>')
            names = " · ".join(Path(rows[i][0]).name for i, _, _ in band)
            # a short trailing row left-hanging reads as a mistake; centre it
            tag = "" if band[0][2] else ' align="center"'
            out += [f"<p{tag}>{' '.join(imgs)}</p>", "",
                    f"<p{tag}><sub>{names}</sub></p>", ""]
    return "\n".join(out).rstrip() + "\n"


def write_readme_gallery(readme: str | Path, figures_dir: str | Path) -> Path:
    """Rewrite the region between the gallery markers, in place."""
    readme = Path(readme)
    text = readme.read_text()
    assert README_START in text and README_END in text, \
        f"{readme}: missing {README_START} / {README_END} markers"
    head, _, rest = text.partition(README_START)
    _, _, tail = rest.partition(README_END)
    body = build_readme_gallery(figures_dir)
    readme.write_text(f"{head}{README_START}\n\n{body}\n{README_END}{tail}")
    return readme
