"""Generate the browsable corpus index from figure-program metadata.

Metadata is read from SOURCE with `ast`, not by importing: listing the corpus
should not cost one render per figure, and a figure that is mid-repair should
still appear in the index rather than silently vanishing from it. That second property is
the reason this is not just a loop over `load_program`.

    build_gallery(figures_dir) -> markdown
    write_gallery(figures_dir) -> path to figures/out/GALLERY.md
    write_readme_gallery(readme, figures_dir) -> the README's thumbnail grid
"""

from __future__ import annotations

import ast
from pathlib import Path

from .regress import artifact_dir, discover_programs

#: subjects in reading order; anything else sorts after, alphabetically
SUBJECT_ORDER = ["complex", "signals", "linalg", "dynamics", "optim",
                 "probability", "statmech", "infotheory", "circuits"]

SUBJECT_BLURB = {
    "complex": "Conformal maps, the Riemann sphere, contour integration.",
    "signals": "Sampling, spectra, and the geometry of transfer functions.",
    "linalg": "Matrices as geometry: the four readings, low rank, conditioning.",
    "dynamics": "Flows, bifurcations, and stochastic trajectories.",
    "optim": "What actually governs convergence.",
    "probability": "Densities under maps, and where the mass really lives.",
    "statmech": "Order parameters and phase transitions.",
    "infotheory": "Typicality, and why the mode is not the story.",
    "circuits": "Transformer internals as computation graphs.",
}


def _string_field(tree: ast.Module, name: str) -> str | None:
    """Read a module-level string assignment without executing the module.

    Handles the two spellings the corpus uses: a bare string, and the
    implicitly-concatenated `NAME = ("a" "b")` form that long CLAIMs take.
    """
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(isinstance(t, ast.Name) and t.id == name for t in node.targets):
            continue
        v = node.value
        if isinstance(v, ast.Constant) and isinstance(v.value, str):
            return v.value
        # ("part " "part") parses as a single Constant, but an explicit
        # a + b concatenation does not; fold that too rather than dropping it.
        if isinstance(v, ast.BinOp) and isinstance(v.op, ast.Add):
            try:
                return ast.literal_eval(v)
            except Exception:
                return None
    return None


def _subject(program: Path, figures_dir: Path) -> str:
    parent = program.parent.resolve()
    return "" if parent == figures_dir.resolve() else parent.name


def _sort_key(subject: str) -> tuple[int, str]:
    return ((SUBJECT_ORDER.index(subject), "") if subject in SUBJECT_ORDER
            else (len(SUBJECT_ORDER), subject))


def _entries(figures_dir: Path) -> dict[str, list[tuple[str, str, str]]]:
    """subject -> sorted [(stem relative to out/, claim, exposition)]."""
    out_root = figures_dir / "out"
    entries: dict[str, list[tuple[str, str, str]]] = {}
    for program in discover_programs(figures_dir):
        tree = ast.parse(program.read_text(), str(program))
        claim = _string_field(tree, "CLAIM") or "_(no CLAIM)_"
        prose = (_string_field(tree, "EXPOSITION")
                 or _string_field(tree, "PROBES")
                 or "_(no EXPOSITION yet)_")
        rel = artifact_dir(program, figures_dir).relative_to(out_root)
        stem = program.stem if str(rel) == "." else str(rel / program.stem)
        entries.setdefault(_subject(program, figures_dir), []).append(
            (stem, claim.strip(), prose.strip()))
    return {k: sorted(v) for k, v in entries.items()}


def build_gallery(figures_dir: str | Path) -> str:
    figures_dir = Path(figures_dir)
    entries = _entries(figures_dir)
    n = sum(len(v) for v in entries.values())
    lines = [
        "# Figure gallery", "",
        f"{n} figures. Generated by `make gallery` — **do not edit.**", "",
        "Each card shows the default render on the theme's white stock; the "
        "`_transparent` SVG is "
        "ink on alpha, for embedding in a document that owns its own ground.",
        "",
    ]
    for subject in sorted(entries, key=_sort_key):
        lines += [f"## {subject or 'unbinned'}", ""]
        if blurb := SUBJECT_BLURB.get(subject):
            lines += [f"*{blurb}*", ""]
        for stem, claim, prose in entries[subject]:
            name = Path(stem).name
            lines += [
                f"### {name}", "",
                f"![{name}]({stem}.png)", "",
                f"**Claim.** {claim}", "",
                prose, "",
                f"[svg]({stem}.svg) · "
                f"[transparent svg]({stem}_transparent.svg) · "
                f"[readback]({stem}.readback.md)", "",
                "---", "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def write_gallery(figures_dir: str | Path) -> Path:
    figures_dir = Path(figures_dir)
    path = figures_dir / "out" / "GALLERY.md"
    path.write_text(build_gallery(figures_dir))
    return path


# --- the README thumbnail grid ---------------------------------------------
#
# Inline <img> in paragraphs, NOT a <table>: GitHub's markdown stylesheet puts
# a 1px border and zebra striping on every table cell in a README, so a table
# grid frames each thumbnail in a grey box and tints alternate rows. Paragraphs
# get no chrome. The cost is that the browser, not us, decides where a row
# wraps -- so rows are justified to land UNDER the column width, never at it.

README_START = "<!-- gallery:start -->"
README_END = "<!-- gallery:end -->"
#: GitHub's README column is ~890px; leave headroom so no row can rewrap
CONTENT_WIDTH_PX = 840
ROW_TARGET_HEIGHT_PX = 230
#: the single collapsed space between two inline <img> tags
_IMG_GAP_PX = 5
#: a flush row is worth nothing if its thumbnails are too small to read; the
#: signals row (three wide figures, span 5.5) justified to 152px before this
MIN_ROW_HEIGHT_PX = 170


def justify_rows(aspects: list[float], content_width: float = CONTENT_WIDTH_PX,
                 target_h: float = ROW_TARGET_HEIGHT_PX,
                 ) -> list[list[tuple[int, int, bool]]]:
    """Justified layout: minimum-raggedness line breaking, Knuth-Plass style.

    Every image in a row shares one height, and the row is solved so its images
    span `content_width` exactly -- so inline <img> tags sit on one baseline and
    the ragged aspect ratios of this corpus (0.88 to 4.07) come out flush.

    Badness is measured in pixels of width. A row of items i..j wants
    `span * target_h` px and has `avail` px; the shortfall

        slack = span * target_h - avail

    is negative when the row cannot fill the width (it renders at target_h and
    leaves a hole) and positive when it over-fills (it renders flush, but
    shrunk). One quadratic penalises both, and a DP over all break points
    minimises the total -- O(n^2) on at most fourteen figures per subject.
    A row that would justify below `MIN_ROW_HEIGHT_PX` is rejected outright:
    flush-but-illegible is not a solution. Every single figure clears that
    floor on its own (the corpus tops out at aspect 4.07), so a partition
    always exists.

    Greedy was the first attempt and it is wrong here, in the specific way
    greedy line-breaking is always wrong: it optimises each row in ignorance of
    the next, so it left seven of the nine subjects ending on a single orphaned
    thumbnail. The DP pays a slightly worse row earlier to avoid the orphan.

    `target_h` is a CEILING, never a height to overshoot: a row that genuinely
    cannot fill (a subject holding one figure) renders at target_h and is
    centred. Letting such a row justify upward turned those subjects into
    300px banners -- the raggedness was vertical, not horizontal.

    Returns rows of (index, height_px, filled); `filled` is False for a row
    that could not span the width, which is the signal to centre it.
    """
    n = len(aspects)
    if not n:
        return []
    prefix = [0.0]
    for a in aspects:
        prefix.append(prefix[-1] + a)

    def avail(i: int, j: int) -> float:
        return content_width - _IMG_GAP_PX * (j - i - 1)

    def badness(i: int, j: int) -> float:
        w = avail(i, j)
        span = prefix[j] - prefix[i]
        if w / span < MIN_ROW_HEIGHT_PX:
            return float("inf")     # flush but illegible is not a solution
        return (span * target_h - w) ** 2

    best = [0.0] + [float("inf")] * n
    cut = [0] * (n + 1)
    for j in range(1, n + 1):
        for i in range(j):
            c = best[i] + badness(i, j)
            if c < best[j]:
                best[j], cut[j] = c, i

    groups, j = [], n
    while j:
        groups.append(list(range(cut[j], j)))
        j = cut[j]
    groups.reverse()

    out = []
    for idx in groups:
        h = avail(idx[0], idx[-1] + 1) / (prefix[idx[-1] + 1] - prefix[idx[0]])
        out.append([(i, int(min(h, target_h)), h <= target_h) for i in idx])
    return out


def _aspect(png: Path) -> float:
    """Fall back to 3:2 for a figure whose baseline is not on disk yet -- the
    grid should degrade, not crash, on a figure that has never been rendered."""
    try:
        from PIL import Image
        with Image.open(png) as im:
            return im.width / im.height
    except Exception:
        return 1.5


def build_readme_gallery(figures_dir: str | Path) -> str:
    figures_dir = Path(figures_dir)
    entries = _entries(figures_dir)
    # the count lives INSIDE the regenerated region -- a hand-written "33
    # figures" on a landing page is wrong the day the 34th lands
    n = sum(len(v) for v in entries.values())
    out = [f"**{n} figures.** Every thumbnail links to its claim, the passage "
           "it serves, and both renders — or browse "
           "[the full gallery](figures/out/GALLERY.md).", ""]
    for subject in sorted(entries, key=_sort_key):
        rows = entries[subject]
        aspects = [_aspect(figures_dir / "out" / f"{stem}.png")
                   for stem, _, _ in rows]
        out += [f"### {subject or 'unbinned'}", ""]
        if blurb := SUBJECT_BLURB.get(subject):
            out += [f"*{blurb}*", ""]
        for band in justify_rows(aspects):
            imgs = []
            for i, h, _ in band:
                stem, _, _ = rows[i]
                name = Path(stem).name
                imgs.append(
                    f'<a href="figures/out/GALLERY.md#{name}">'
                    f'<img src="figures/out/{stem}.png" '
                    f'alt="{name}" title="{name}" height="{h}"></a>')
            # The name rides `title` (hover) and `alt`, not a caption strip:
            # a run of underscored names centred under a row lines up with no
            # image in it, so it read as a fourth ragged element per row. The
            # grid is an index -- the click goes to the name.
            tag = "" if band[0][2] else ' align="center"'
            out += [f"<p{tag}>{' '.join(imgs)}</p>", ""]
    return "\n".join(out).rstrip() + "\n"


def write_readme_gallery(readme: str | Path, figures_dir: str | Path) -> Path:
    """Rewrite the region between the gallery markers, in place."""
    readme = Path(readme)
    text = readme.read_text()
    assert README_START in text and README_END in text, \
        f"{readme}: missing {README_START} / {README_END} markers"
    head, _, rest = text.partition(README_START)
    _, _, tail = rest.partition(README_END)
    body = build_readme_gallery(figures_dir)
    readme.write_text(f"{head}{README_START}\n\n{body}\n{README_END}{tail}")
    return readme
