"""Generate the browsable corpus index from figure-program metadata.

Metadata is read from SOURCE with `ast`, not by importing: listing 33 figures
should not cost 33 renders, and a figure that is mid-repair should still appear
in the index rather than silently vanishing from it. That second property is
the reason this is not just a loop over `load_program`.

    build_gallery(figures_dir) -> markdown
    write_gallery(figures_dir) -> path to figures/out/GALLERY.md
"""

from __future__ import annotations

import ast
from pathlib import Path

from .regress import artifact_dir, discover_programs

#: subjects in reading order; anything else sorts after, alphabetically
SUBJECT_ORDER = ["complex", "signals", "linalg", "dynamics", "optim",
                 "probability", "statmech", "infotheory", "circuits"]

SUBJECT_BLURB = {
    "complex": "Conformal maps, the Riemann sphere, contour integration.",
    "signals": "Sampling, spectra, and the geometry of transfer functions.",
    "linalg": "Matrices as geometry: the four readings, low rank, conditioning.",
    "dynamics": "Flows, bifurcations, and stochastic trajectories.",
    "optim": "What actually governs convergence.",
    "probability": "Densities under maps, and where the mass really lives.",
    "statmech": "Order parameters and phase transitions.",
    "infotheory": "Typicality, and why the mode is not the story.",
    "circuits": "Transformer internals as computation graphs.",
}


def _string_field(tree: ast.Module, name: str) -> str | None:
    """Read a module-level string assignment without executing the module.

    Handles the two spellings the corpus uses: a bare string, and the
    implicitly-concatenated `NAME = ("a" "b")` form that long CLAIMs take.
    """
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(isinstance(t, ast.Name) and t.id == name for t in node.targets):
            continue
        v = node.value
        if isinstance(v, ast.Constant) and isinstance(v.value, str):
            return v.value
        # ("part " "part") parses as a single Constant, but an explicit
        # a + b concatenation does not; fold that too rather than dropping it.
        if isinstance(v, ast.BinOp) and isinstance(v.op, ast.Add):
            try:
                return ast.literal_eval(v)
            except Exception:
                return None
    return None


def _subject(program: Path, figures_dir: Path) -> str:
    parent = program.parent.resolve()
    return "" if parent == figures_dir.resolve() else parent.name


def _sort_key(subject: str) -> tuple[int, str]:
    return ((SUBJECT_ORDER.index(subject), "") if subject in SUBJECT_ORDER
            else (len(SUBJECT_ORDER), subject))


def build_gallery(figures_dir: str | Path) -> str:
    figures_dir = Path(figures_dir)
    out_root = figures_dir / "out"
    entries: dict[str, list[tuple[str, str, str]]] = {}

    for program in discover_programs(figures_dir):
        tree = ast.parse(program.read_text(), str(program))
        claim = _string_field(tree, "CLAIM") or "_(no CLAIM)_"
        prose = (_string_field(tree, "EXPOSITION")
                 or _string_field(tree, "PROBES")
                 or "_(no EXPOSITION yet)_")
        rel = artifact_dir(program, figures_dir).relative_to(out_root)
        stem = program.stem if str(rel) == "." else str(rel / program.stem)
        entries.setdefault(_subject(program, figures_dir), []).append(
            (stem, claim.strip(), prose.strip()))

    n = sum(len(v) for v in entries.values())
    lines = [
        "# Figure gallery", "",
        f"{n} figures. Generated by `make gallery` — **do not edit.**", "",
        "Each card shows the cream render because it reads better as a card; "
        "the transparent SVG is the one to embed in a document.", "",
    ]
    for subject in sorted(entries, key=_sort_key):
        lines += [f"## {subject or 'unbinned'}", ""]
        if blurb := SUBJECT_BLURB.get(subject):
            lines += [f"*{blurb}*", ""]
        for stem, claim, prose in sorted(entries[subject]):
            name = Path(stem).name
            lines += [
                f"### {name}", "",
                f"![{name}]({stem}_paper.png)", "",
                f"**Claim.** {claim}", "",
                prose, "",
                f"[transparent svg]({stem}.svg) · "
                f"[cream svg]({stem}_paper.svg) · "
                f"[readback]({stem}.readback.md)", "",
                "---", "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def write_gallery(figures_dir: str | Path) -> Path:
    figures_dir = Path(figures_dir)
    path = figures_dir / "out" / "GALLERY.md"
    path.write_text(build_gallery(figures_dir))
    return path
