"""The DFT matrix drawn as what it is: a gallery of sampled sinusoids.

Strang's move, made literal: F_8 is not a table of numbers but eight
column waveforms — cos ramps of increasing frequency, each column k
drawn as a mini stem plot down the matrix and bound by hue to its
generating root of unity omega^k. The right panel closes the loop: a
signal x and its spectrum |X_k|, spectrum stems wearing the SAME hues,
so "which columns compose x" is read as color, not computed. The cell
geometry is local arithmetic (top-left origin, row n down, column k
right); matrices need no primitive, only addresses.
"""

import numpy as np

from figlib.color import to_hex
from figlib.figure import Connector, Figure, Panel
from figlib.format import WIDE
from figlib.gates import Checks
from figlib.plots import Ticks, axis, linear, markers, stems
from figlib.scene import AngleMark, Curve, MathLabel, Point, Scene
from figlib.style import Role
from figlib.theme import RISO

THEME = RISO
FORMAT = WIDE

CLAIM = (
    "The 8-point DFT matrix is a basis gallery: column k, drawn as a mini "
    "waveform, is the complex exponential of frequency k sampled at n = "
    "0..7 and generated by the k-th root of unity (same hue); the signal "
    "x[n] = cos(2 pi 2n/8) + 0.4 sin(2 pi 3n/8) is the hue-matched weighted "
    "sum of exactly the columns its spectrum |X_k| lights up, and F is "
    "unitary up to 1/8."
)

EXPOSITION = """
Strang's reading of the DFT matrix, made literal: F is not a formula
for computing a spectrum, it is a change of basis, and its columns are
the basis vectors. Column k is the complex exponential of frequency k,
sampled at n = 0..N-1 -- a discrete sinusoid generated by raising the
N-th root of unity omega to the power k, one value per row. A signal
x[n] is some combination of these N columns, and the DFT is exactly the
bookkeeping that finds the combination: X_k is the coefficient column k
must carry so that (1/N) sum_k X_k f_k reconstructs x. Read that way,
|X_k| large means "x leans heavily on column k's waveform" and |X_k| = 0
means "column k contributes nothing" -- the spectrum is a set of weights
on a fixed gallery of waveforms, not a separate object computed from x
by a different kind of arithmetic. Unitarity of F/sqrt(N) is what makes
those weights well-defined and recoverable at all.
"""

PARAMS = {
    "N": 8,
    "cos_bin": 2, "cos_amp": 1.0,
    "sin_bin": 3, "sin_amp": 0.4,
    "stem_half": 0.42,     # cell half-width a unit sample reaches
    "spec_scale": 0.55,    # drawn units per unit of |X|
    "x_base": 5.0,         # baseline of the x[n] strip in panel b
    "root_c": (2.0, -2.5), "root_r": 1.5,
}


def _hue(k: int, N: int) -> str:
    """Column k's identity: the phase channel at the k-th root's angle."""
    ang = 2 * np.pi * k / N
    ang = float(np.angle(np.exp(1j * ang)))     # wrap into [-pi, pi]
    return to_hex(tuple(float(v) for v in THEME.phase(ang, 1.0)))


def compute(p):
    N = p["N"]
    n = np.arange(N)
    x = (p["cos_amp"] * np.cos(2 * np.pi * p["cos_bin"] * n / N)
         + p["sin_amp"] * np.sin(2 * np.pi * p["sin_bin"] * n / N))
    X = np.fft.fft(x)
    F = np.exp(2j * np.pi * np.outer(n, n) / N)    # synthesis matrix, F_nk
    return {"params": p, "n": n, "x": x, "X": X, "F": F,
            "gallery": F.real,                      # what the cells draw
            "hues": [_hue(k, N) for k in range(N)]}


def _matrix_panel(g) -> Scene:
    p = g["params"]
    N = p["N"]
    s = Scene(xlim=(-1.35, 9.05), ylim=(-4.45, 9.35))

    def center(nr: int, k: int) -> tuple[float, float]:
        return (k + 0.5, N - (nr + 0.5))            # row n grows DOWNWARD

    # brackets: the canonical [ ] construction, 3 segments each
    for xb, d in ((-0.35, 0.25), (N + 0.35, -0.25)):
        s.add(Curve(np.array([[xb + d, 0.0], [xb, 0.0], [xb, N], [xb + d, N]]),
                    role=Role.ANNOTATION))
    # per-column baseline hairline, then the waveform stems off it
    for k in range(N):
        cx = k + 0.5
        s.add(Curve(np.array([[cx, 0.06], [cx, N - 0.06]]), role=Role.FRAME))
        col = g["hues"][k]
        # the waveform BEHIND the samples: a thin polyline through the
        # tips, so a column reads as one sinusoid, not eight dashes (and
        # columns 2 and 6 are visibly the same cosine — aliasing, drawn)
        tips = np.array([(cx + p["stem_half"] * g["gallery"][nr, k],
                          center(nr, k)[1]) for nr in range(N)])
        s.add(Curve(tips, color=col, width_scale=0.55))
        for nr in range(N):
            _, cy = center(nr, k)
            v = p["stem_half"] * g["gallery"][nr, k]
            if abs(v) > 1e-12:
                s.add(Curve(np.array([[cx, cy], [cx + v, cy]]),
                            color=col, width_scale=0.9))
            s.add(Point((cx + v, cy), color=col, radius_scale=0.55))
        s.add(MathLabel(str(k), (cx, N + 0.22), color=col, ha="center",
                        va="bottom", size_pt=8.5))
    s.add(MathLabel(r"k", (N / 2, N + 0.95), role=Role.ANNOTATION,
                    ha="center", va="bottom"))
    s.add(MathLabel(r"n", (-0.95, N / 2), role=Role.ANNOTATION,
                    ha="right", va="center"))
    s.add(MathLabel(r"\mathrm{Re}\,F_{nk}", (-1.0, N + 0.95),
                    role=Role.ANNOTATION, ha="left", va="bottom"))

    # the generator: roots of unity, one dot per column, same hues
    cx, cy = p["root_c"]
    r = p["root_r"]
    th = np.linspace(0, 2 * np.pi, 128)
    s.add(Curve(np.column_stack([cx + r * np.cos(th), cy + r * np.sin(th)]),
                role=Role.CONSTRUCTION, closed=True))
    for k in range(N):
        a = 2 * np.pi * k / N
        s.add(Point((cx + r * np.cos(a), cy + r * np.sin(a)),
                    color=g["hues"][k]))
    s.add(AngleMark((cx, cy), (1.0, 0.0), (np.cos(2 * np.pi / N),
                                           np.sin(2 * np.pi / N)),
                    radius=0.5 * r))
    s.add(MathLabel(r"\omega", (cx + r * np.cos(2 * np.pi / N),
                                cy + r * np.sin(2 * np.pi / N)),
                    ha="left", va="bottom", offset_px=(5, -3)))
    s.add(MathLabel(r"1", (cx + r, cy), ha="left", va="top",
                    offset_px=(5, 4)))
    s.add(MathLabel(r"F_{nk} = \omega^{nk}", (5.6, -1.9),
                    role=Role.ANNOTATION, ha="left", va="center"))
    s.add(MathLabel(r"\omega = e^{2\pi i/8}", (5.6, -2.9),
                    role=Role.ANNOTATION, ha="left", va="center"))
    return s


def _signal_panel(g) -> Scene:
    p = g["params"]
    N = p["N"]
    yb = p["x_base"]
    s = Scene(xlim=(-1.6, 8.7), ylim=(-1.35, 7.55))
    tk_none = Ticks(values=np.arange(N), positions=np.arange(N),
                    labels=tuple([""] * N))
    tk_k = Ticks(values=np.arange(N), positions=np.arange(N),
                 labels=tuple(str(k) for k in range(N)))

    # x[n]: the time-domain strip
    s.items += axis(linear(0, N - 1), orient="x", at=yb, side=-1,
                    ticks=tk_none, tick_len=0.09, tick_labels=False,
                    extend=(0.35, 0.5), label=r"n", arrow=True)
    s.items += stems(g["n"], yb + g["x"], baseline=yb, size=0.09,
                     role=Role.CONTENT)
    s.add(MathLabel(r"x[n]", (0.0, yb + 1.3), role=Role.CONTENT,
                    ha="right", va="center", offset_px=(-8, 0)))

    # |X_k|: the spectrum, stems wearing the gallery hues
    s.items += axis(linear(0, N - 1), orient="x", at=0.0, side=-1,
                    ticks=tk_k, tick_len=0.09, extend=(0.35, 0.5),
                    label=r"k", arrow=True)
    for k in range(N):
        s.items += stems([k], [p["spec_scale"] * abs(g["X"][k])],
                         size=0.09, color=g["hues"][k])
    s.add(MathLabel(r"|X_k|", (0.0, 2.5), role=Role.CONTENT,
                    ha="right", va="center", offset_px=(-8, 0)))
    return s


def build(g):
    return Figure(
        panels=[Panel(_matrix_panel(g), tag=r"[a]", width_frac=0.55),
                Panel(_signal_panel(g), tag=r"[b]")],
        connectors=[Connector(0, 1, kind="map",
                              label=r"x = \tfrac{1}{8}\textstyle\sum_k X_k f_k")],
    )


def assertions(g):
    p = g["params"]
    N = p["N"]
    ck = Checks()
    # unitarity up to 1/N — the algebraic fact the gallery depicts
    err = np.abs(g["F"] @ g["F"].conj().T / N - np.eye(N)).max()
    ck.check(err < 1e-12, f"F F*/N deviates from I by {err:.2e}")
    # the drawn spectrum is the fft of the drawn signal
    ck.check(bool(np.allclose(g["X"], np.fft.fft(g["x"]))),
             "drawn |X_k| stems are not the DFT of the drawn x[n]")
    # conjugate symmetry: x is real, so the spectrum must pair k with N-k
    ck.check(bool(np.allclose(g["X"][1:], np.conj(g["X"][1:][::-1]))),
             "spectrum lacks the conjugate symmetry a real x forces")
    # x really is the hue-matched synthesis: 1/N sum_k X_k F[:, k]
    resyn = (g["F"] @ g["X"]) / N
    ck.check(bool(np.allclose(resyn.real, g["x"])) and
             float(np.abs(resyn.imag).max()) < 1e-12,
             "x != (1/N) F X — the connector's equation fails on the arrays")
    # the live bins are exactly the two the construction put there
    live = {k for k in range(N) if abs(g["X"][k]) > 1e-9}
    ck.check(live == {p["cos_bin"], N - p["cos_bin"],
                      p["sin_bin"], N - p["sin_bin"]},
             f"live spectrum bins {sorted(live)} are not the constructed ones")
    ck.done()
